
export const startups = [
  {
    title: 'IsabiVTU Technology',
    description: 'A platform for seamless virtual top-up and bill payments. Making everyday transactions easier.',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'fintech app',
    tags: ['FinTech', 'Bill Payment', 'Mobile Wallet', 'Technology'],
    url: 'https://isabivtu.com.ng',
  },
  {
    title: 'IsabiWP Cloud Nigeria',
    description: 'A web hosting provider providing premium web and cloud hosting solutions in Africa',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'wordpress development',
    tags: ['Web Hosting', 'Domain Name', 'Cloud'],
    url: 'https://isabiwp.com.ng',
  },
  {
    title: 'IsabiPay Technology',
    description: 'A all in one payment solution for businesses and individual in Nigeria.',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'payment gateway',
    tags: ['Payment', 'API', 'Gateway', 'Technology'],
    url: 'https://isabipay.com.ng',
  },
  {
    title: 'Inwang',
    description: 'A platform that connect buyers to farmers across Africa',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'startup logo',
    tags: ['Technology', 'Community', 'AgriTech'],
    url: 'https://www.iwang.ng',
  },
  {
    title: 'Hack51 Africa',
    description: 'An innovative platform fostering tech talent and solutions in Africa.',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'tech community',
    tags: ['Technology', 'Hackathon', 'Startups'],
    url: 'https://hack51.africa',
  },
  {
    title: 'CreatorPass',
    description: 'A platform that Allow Creators monetize their art without middlemen.',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'creator economy',
    tags: ['SaaS', 'Creators', 'Monetize'],
    url: 'https://creatorpass.net',
  },
  {
    title: 'Isabi.click',
    description: 'A powerful URL shortening and management service.',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'link management',
    tags: ['SaaS', 'Utility', 'URL Shortener'],
    url: 'https://isabi.click',
  },
  {
    title: 'IsabiRead AI',
    description: 'An innovative platform that Turn your PDFs into Audiobooks using AI.',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'ebook reader',
    tags: ['EdTech', 'Reading', 'SaaS'],
    url: 'https://www.isabiread.icu',
  },
  {
    title: 'Chopfoods',
    description: 'An online platform for food ordering and delivery services.',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'food delivery',
    tags: ['FoodTech', 'E-commerce', 'Delivery'],
    url: 'https://chopfoods.online',
  },
  {
    title: 'Gadlock',
    description: 'Secure Your Electronics at Your Fingertips',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'digital services',
    tags: ['SaaS', 'Digital', 'Technology'],
    url: 'https://gadlock.com',
  },
  {
    title: 'MyAza',
    description: 'An innovative platform for financial services and technology.',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'financial technology',
    tags: ['FinTech', 'Multiple currencies Wallet'],
    url: 'https://myaza.co',
  },
  {
    title: 'IsabiPitch',
    description: 'A platform for entrepreneurs to create and share pitch decks.',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'presentation startup',
    tags: ['SaaS', 'Startup', 'Pitch Deck'],
    url: 'https://www.isabipitch.icu',
  }
];
